# permissions for end users to edit publishers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: publisher-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: eventd-operator
    app.kubernetes.io/part-of: eventd-operator
    app.kubernetes.io/managed-by: kustomize
  name: publisher-editor-role
rules:
- apiGroups:
  - eventd.redrvm.cloud
  resources:
  - publishers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - eventd.redrvm.cloud
  resources:
  - publishers/status
  verbs:
  - get
